networks:
  vc-network:
    driver: bridge

volumes:
  prometheus_data:

services:
  postgres:
    container_name: vacancy_control_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rocket
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - vc-network
    ports:
      - 9090:9090